name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v2

      # install dependencies, start the app,
      # and run E2E tests using Cypress GitHub action
      # https://github.com/cypress-io/github-action
      - name: Run tests 🧪
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:8080'

      # run two Cypress instances at the same time
      # so they truly chat with each other
      - name: Run 2 Cypresses 🧪
        uses: cypress-io/github-action@v2
        with:
          # we already have installed everything
          install: false
          start: npm start
          wait-on: 'http://localhost:8080'
          command: npm run chat
